version: '3'
services:
  db:
    container_name: mysql
    image: mysql
    platform: linux/amd64
    environment:
      SPRING_PROFILES_ACTIVE: local
      MYSQL_DATABASE: reservation_system
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_ROOT_HOST: root
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
