version: '3'
services:
  db:
    container_name: mysql
    image: mysql
    platform: linux/amd64
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: test
      MYSQL_DATABASE: reservation_system_test
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_ROOT_HOST: root
    ports:
      - "3306:3306"
    volumes:
      - "./mysql_data:/var/lib/mysql"

