version: '3'
services:
  db:
    container_name: mysql
    image: mysql
    platform: linux/amd64
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: local
      MYSQL_DATABASE: reservation_system_test
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_ROOT_HOST: root
    ports:
      - "3306:3306"
    volumes:
      - "./mysql_data:/var/lib/mysql"

  spring-app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/reservation_system_test?useSSL=false&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql123
      SPRING_DATASOURCE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DDL_AUTO: update
    ports:
      - "3000:3000"
    restart: always
    links:
      - db
    depends_on:
      - db
