version: '3'
services:
  db:
    container_name: mysql
    image: mysql
    platform: linux/amd64
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_DATABASE: reservation_system_test
      MYSQL_ROOT_PASSWORD: /run/secrets/SPRING_DATASOURCE_PASSWORD
      MYSQL_ROOT_HOST: /run/secrets/MYSQL_ROOT_HOST
    ports:
      - "3306:3306"
    volumes:
      - "./mysql_data:/var/lib/mysql"

  spring-app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: /run/secrets/SPRING_DATASOURCE_URL
      SPRING_DATASOURCE_USERNAME: /run/secrets/MYSQL_ROOT_HOST
      SPRING_DATASOURCE_PASSWORD: /run/secrets/SPRING_DATASOURCE_PASSWORD
      SPRING_DATASOURCE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DDL_AUTO: update
    ports:
      - "3000:3000"
    restart: always
    links:
      - db
    depends_on:
      - db
